spring:
  datasource:
    url: jdbc:sqlserver://localhost\SQLEXPRESS:49170;database=wise-studies;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 08240
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect

